name: 'AI PR Reviewer'
description: 'AI-powered pull request reviewer and summarizer'
inputs:
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  review_simple_changes:
    description: 'Review simple changes'
    required: false
    default: 'true'
  review_comment_lgtm:
    description: 'Review LGTM comments'
    required: false
    default: 'true'
  disable_review:
    description: 'Disable review'
    required: false
    default: 'false'
  disable_release_notes:
    description: 'Disable release notes'
    required: false
    default: 'false'
  max_files:
    description: 'Maximum number of files to review'
    required: false
    default: '50'
  path_filters:
    description: 'Path filters for files to review'
    required: false
    default: |
      !dist/**
      !**/*.app
      !**/*.bin
      !**/*.bz2
      !**/*.class
      !**/*.db
      !**/*.csv
      !**/*.tsv
      !**/*.dat
      !**/*.dll
      !**/*.dylib
      !**/*.egg
      !**/*.glif
      !**/*.gz
      !**/*.xz
      !**/*.zip
      !**/*.7z
      !**/*.rar
      !**/*.zst
      !**/*.ico
      !**/*.jar
      !**/*.tar
      !**/*.war
      !**/*.lo
      !**/*.log
      !**/*.mp3
      !**/*.wav
      !**/*.wma
      !**/*.mp4
      !**/*.avi
      !**/*.mkv
      !**/*.wmv
      !**/*.m4a
      !**/*.m4v
      !**/*.3gp
      !**/*.3g2
      !**/*.rm
      !**/*.mov
      !**/*.flv
      !**/*.iso
      !**/*.swf
      !**/*.flac
      !**/*.nar
      !**/*.o
      !**/*.ogg
      !**/*.otf
      !**/*.p
      !**/*.pdf
      !**/*.doc
      !**/*.docx
      !**/*.xls
      !**/*.xlsx
      !**/*.ppt
      !**/*.pptx
      !**/*.pkl
      !**/*.pickle
      !**/*.pyc
      !**/*.pyd
      !**/*.pyo
      !**/*.pub
      !**/*.pem
      !**/*.rkt
      !**/*.so
      !**/*.ss
      !**/*.eot
      !**/*.exe
      !**/*.pb.go
      !**/*.lock
      !**/*.ttf
      !**/*.yaml
      !**/*.yml
      !**/*.cfg
      !**/*.toml
      !**/*.ini
      !**/*.mod
      !**/*.sum
      !**/*.work
      !**/*.json
      !**/*.mmd
      !**/*.svg
      !**/*.jpeg
      !**/*.jpg
      !**/*.png
      !**/*.gif
      !**/*.bmp
      !**/*.tiff
      !**/*.webm
      !**/*.woff
      !**/*.woff2
      !**/*.dot
      !**/*.md5sum
      !**/*.wasm
      !**/*.snap
      !**/*.parquet
      !**/gen/**
      !**/_gen/**
      !**/generated/**
      !**/@generated/**
      !**/vendor/**
      !**/*.min.js
      !**/*.min.js.map
      !**/*.min.js.css
      !**/*.tfstate
      !**/*.tfstate.backup
  system_message:
    description: 'Custom system message for the AI'
    required: false
    default: ''
  summarize:
    description: 'Custom summarize prompt'
    required: false
    default: ''
  summarize_release_notes:
    description: 'Custom release notes prompt'
    required: false
    default: ''
  openai_base_url:
    description: 'OpenAI API base URL'
    required: false
    default: 'https://api.openai.com'
  openai_light_model:
    description: 'OpenAI light model'
    required: false
    default: 'gpt-3.5-turbo'
  openai_heavy_model:
    description: 'OpenAI heavy model'
    required: false
    default: 'gpt-4'
  openai_model_temperature:
    description: 'OpenAI model temperature'
    required: false
    default: '0.0'
  openai_retries:
    description: 'OpenAI retries'
    required: false
    default: '5'
  openai_timeout_ms:
    description: 'OpenAI timeout in milliseconds'
    required: false
    default: '360000'
  openai_concurrency_limit:
    description: 'OpenAI concurrency limit'
    required: false
    default: '6'
  github_concurrency_limit:
    description: 'GitHub concurrency limit'
    required: false
    default: '6'
  language:
    description: 'Language for the AI'
    required: false
    default: 'en-US'
  bot_icon:
    description: 'Bot icon'
    required: false
    default:
      '<img src="https://avatars.githubusercontent.com/in/347564?s=41"
      alt="Image description" width="20" height="20">'
runs:
  using: 'node16'
  main: 'lib/index.js'
